
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HOTEL_MANAGEMENT.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Hotel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hotel()
    {

        this.Comments = new HashSet<Comment>();

        this.Rooms = new HashSet<Room>();

    }


    public int Id_Hotel { get; set; }

    public string Name_Hotel { get; set; }

    public string Address_Hotel { get; set; }

    public string City_Hotel { get; set; }

    public int Stars { get; set; }

    public Nullable<int> Id_user { get; set; }

    public string Description_Hotel { get; set; }

    public string Image_Hotel { get; set; }

    public Nullable<int> Number_Room { get; set; }

    public string Telephone { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comment> Comments { get; set; }

    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Room> Rooms { get; set; }

}

}
